### ISSUE TITLE
Eq.7 in the paper

### ISSUE THREAD

**Issue by zjhJOJO** [LMozart/ECCV2024-GCS-BEG#2]
Hi, thanks for you excellent work. I noticed a potential typo error in Eq.7. Given F_\theta denotes a Denoiser (w.r.t. x_t) formulated by one-step DDIM sampling, should x_{\pi, t} be corrected as x_{\pi} in Eq.7? Looking forward to your reply, thanks.

**Comment by LMozart** [comment]
Hi. Yes, you are right—it is a typo. It should align with Table 1. Thank you for your correction.
