### ISSUE TITLE
Question about Eq.(20) and Proof of Lemma 1

### ISSUE THREAD

**Issue by zjhJOJO** [LMozart/ECCV2024-GCS-BEG#4]
Thank you for your excellent work. I have a question regarding L_{cc} and its corresponding proof in appendix. Specifically, in L_{cc}, you use the unconditional prompt to predict x_e from t with G_{\theta}, however, in the proof, conditional prompt y is used in G_{\theta} instead. Could you help clarify this? Thank you :D.

**Comment by LMozart** [comment]
Hello, and thank you for highlighting this issue. In the proof, the condition y is included to account for a more general case. In the special case where y is null-text, it is identical to L_cc. However, L_cc can also be text-conditioned, which may introduce some variation in the generated results. The main point here is to ensure that the condition remains consistent in both terms of L_cc.
